### ISSUE TITLE
help me out

### ISSUE THREAD

**Issue by ayush8009** [hunterbdm/ANBAIO2captcha#1]
getting this error 

![2](https://user-images.githubusercontent.com/29464952/29001123-7aae22c2-7a9d-11e7-88b7-8a4d6cab8205.PNG)

**Comment by hunterbdm** [comment]
You need to select one of the listed sites by the number (0-7)

**Comment by hunterbdm** [comment]
Also you might want to reset your apikey

**Comment by ayush8009** [comment]
sir i also want aiobot can you please provide ??
